language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install build-essential

before_script:
# Hack to get gtest
  - mkdir lib
  - cd lib
  - wget https://googletest.googlecode.com/files/gtest-1.6.0.zip
  - unzip gtest-1.6.0.zip
  - mv gtest-1.6.0 com.googlecode.googletest
  - cd ../
# Standard pre-build  
  - mkdir build
  - cd build
  - cmake ../

script:
  - make alltest

after_script:
  - cd ..
  - rm -rf build
  - rm -rf lib