language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install build-essential
  - sudo apt-get install libgtest-dev

before_script:
# Hack to build gtest
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
# Standard pre-build  
  - mkdir build
  - cd build
  - cmake ../
  
script:
  - make
  - ./run_tests

after_script:
  - cd ..
  - rm -rf build