language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install build-essential
  - sudo apt-get install libgtest-dev

before_script:
  - mkdir build
  - cd build
  - cmake ../
  
script:
  - make
  - ./run_tests

after_script:
  - cd ..
  - rm -rf build